[package]
name = "state_keeper"
version = "0.1.0"
authors = ["HAOYUatHZ <haoyu@protonmail.com>"]
edition = "2018"

[dependencies]
config_rs = { package = "config", version = "0.10.1" }
dotenv = "0.15.0"
env_logger = "0.5"
lazy_static = "1.4.0"
log = "0.4"
serde = { version = "1.0.124", features = ["derive"] }
serde_derive = "1.0.90"
serde_json = "1.0.64"
franklin_crypto = { package = "franklin-crypto", git = "https://github.com/matter-labs/franklin-crypto.git", branch ="beta"}
fnv = "1.0.7"
regex = "1"
anyhow = "1.0.39"
num-bigint = {version = "0.2.2", features = ["rand"]}
#num-bigint = "0.4.0"
rayon = "1.5.0"
itertools = "0.10.0"
rand = "0.8.3"
poseidon-rs = { version = "0.0.8"}
ff = {package="ff_ce", version="0.11", features = ["derive"]}
babyjubjub-rs = { version = "0.0.8", features = ["aarch64"], default-features = false}
#babyjubjub-rs = { version = "0.0.8"}
hex = "0.4.3"
arrayref = "0.3.6"
rust_decimal = { version = "1.10.3", features = ["serde_json"] }

[[bin]]
name = "state_keeper"
path = "src/bin/main.rs"

[[bin]]
name = "test_export_circuit"
path = "tests/test_export_circuit.rs"

[[bin]]
name = "test_global_state"
path = "tests/test_global_state.rs"

[features]
default = []
